import type { StaticJsonSchema } from "@pi-oc2/core/domain";
import { renderOpenCode2ToolInput } from "./render-opencode2-schema.js";

/** The commit-pinned OpenCode dev host, plugin, and Promise tool-domain contract. */
export const OPENCODE2_TARGET_PROFILE = "opencode2-dev-18204+plugin-dev-18204+promise-tool-domain" as const;

/** One statically described Promise-domain tool paired with its copied portable executor. */
export interface OpenCode2PreparedTool {
  readonly name: string;
  readonly description: string;
  readonly schema: StaticJsonSchema;
  readonly executorTargetPath: string;
}

/** One copied skill registered by the Promise skill domain during plugin setup. */
export interface OpenCode2PreparedSkill {
  readonly name: string;
  readonly description?: string;
  readonly targetPath: string;
  readonly content: string;
}

function generatedTypeScriptHeader(sourceHash: string): string {
  return `/**
 * Generated by @pi-oc2/target-opencode2@0.1.0.
 * Source SHA-256: ${sourceHash}
 * Target profile: ${OPENCODE2_TARGET_PROFILE}
 * Generated files are disposable. Edit pioc.port.json or portable modules instead.
 */`;
}

function localPortableImportSpecifier(targetPath: string): string {
  const normalized = targetPath.replaceAll("\\", "/").replace(/^\.\//u, "");
  return `./${normalized}`;
}

function emitOpenCode2ToolRegistration(entry: OpenCode2PreparedTool, index: number): RenderedToolRegistration {
  const input = renderOpenCode2ToolInput(entry.schema);
  if (!input.ok) return input;
  return {
    ok: true,
    source: `    await ctx.tool.transform((draft) => {
      draft.add({
        name: ${JSON.stringify(entry.name)},
        description: ${JSON.stringify(entry.description)},
        input: ${input.expression},
        options: { codemode: false },
        async execute(input, toolContext) {
          const session = await ctx.session.get({ sessionID: toolContext.sessionID });
          const pendingProgress: Promise<void>[] = [];
          const result = await executePortableTool${index}(input, {
            cwd: session.location.directory,
            signal: new AbortController().signal,
            sessionId: toolContext.sessionID,
            update(update) {
              pendingProgress.push(toolContext.progress({
                ...(update.text === undefined ? {} : { title: update.text }),
                ...(update.metadata === undefined ? {} : { metadata: update.metadata }),
              }));
            },
          });
          await Promise.all(pendingProgress);
          return {
            content: result.text,
            ...(result.metadata === undefined ? {} : { metadata: result.metadata }),
          };
        },
      });
    });`,
  };
}

type RenderedToolRegistration =
  | { readonly ok: true; readonly source: string }
  | { readonly ok: false; readonly message: string };

/** Emits the commit-pinned Promise server plugin with native tool and skill registration. */
export function emitOpenCode2Server(
  pluginId: string,
  sourceHash: string,
  tools: readonly OpenCode2PreparedTool[],
  skills: readonly OpenCode2PreparedSkill[],
): { readonly ok: true; readonly source: string } | { readonly ok: false; readonly toolName: string; readonly message: string } {
  const toolRegistrations: string[] = [];
  for (const [index, entry] of tools.entries()) {
    const registration = emitOpenCode2ToolRegistration(entry, index);
    if (!registration.ok) return { ok: false, toolName: entry.name, message: registration.message };
    toolRegistrations.push(registration.source);
  }
  const skillRegistrations = skills.map((skill) => `    await ctx.skill.transform((draft) => {
      draft.add({
        id: Skill.ID.make(${JSON.stringify(`${pluginId}:${skill.name}`)}),
        name: Skill.Name.make(${JSON.stringify(skill.name)}),${skill.description === undefined ? "" : `
        description: ${JSON.stringify(skill.description)},`}
        location: Skill.Info.fields.location.make(
          fileURLToPath(new URL(${JSON.stringify(`./${skill.targetPath}`)}, import.meta.url)),
        ),
        content: ${JSON.stringify(skill.content)},
      });
    });`);
  const setupStatements = [...toolRegistrations, ...skillRegistrations];
  const imports = [
    `import { Plugin${skills.length === 0 ? "" : ", Skill"} } from "@opencode-ai/plugin";`,
    ...(tools.length === 0 ? [] : [`import { Schema } from "effect";`]),
    ...(skills.length === 0 ? [] : [`import { fileURLToPath } from "node:url";`]),
    ...tools.map(
      (entry, index) => `import executePortableTool${index} from ${JSON.stringify(localPortableImportSpecifier(entry.executorTargetPath))};`,
    ),
  ];

  return {
    ok: true,
    source: `${generatedTypeScriptHeader(sourceHash)}
${imports.join("\n")}

export default Plugin.define({
  id: ${JSON.stringify(pluginId)},
  async setup(ctx) {${setupStatements.length === 0 ? "" : `
${setupStatements.join("\n")}
  `}},
});
`,
  };
}

/** Emits the separate native TUI plugin through its own Promise `Plugin.define` root. */
export function emitOpenCode2Tui(pluginId: string, sourceHash: string, overrideTargetPaths: readonly string[]): string {
  const imports = overrideTargetPaths.map(
    (targetPath, index) => `import applyOpenCode2TuiOverride${index} from ${JSON.stringify(localPortableImportSpecifier(targetPath))};`,
  );
  const calls = overrideTargetPaths.map(
    (_targetPath, index) => `    await applyOpenCode2TuiOverride${index}(ctx);`,
  );
  return `${generatedTypeScriptHeader(sourceHash)}
import { Plugin } from "@opencode-ai/plugin/tui";
${imports.join("\n")}${imports.length === 0 ? "" : "\n"}
export default Plugin.define({
  id: ${JSON.stringify(pluginId)},
  async setup(ctx) {${calls.length === 0 ? "" : `
${calls.join("\n")}
  `}},
});
`;
}

function stableJsonValue(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stableJsonValue);
  if (typeof value !== "object" || value === null) return value;
  return Object.fromEntries(
    Object.entries(value)
      .filter(([, entry]) => entry !== undefined)
      .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
      .map(([key, entry]) => [key, stableJsonValue(entry)]),
  );
}

function generatedOpenCode2PackageName(pluginId: string): string {
  const segment = pluginId.toLowerCase().replace(/[^a-z0-9._-]+/gu, "-").replace(/^-+|-+$/gu, "") || "plugin";
  return `@pi-oc2/generated-opencode2-${segment}`;
}

/** Emits the package manifest pinned to the runnable dev Promise API and Effect Schema version. */
export function emitOpenCode2PackageJson(pluginId: string, sourceHash: string): string {
  return `${JSON.stringify(
    stableJsonValue({
      name: generatedOpenCode2PackageName(pluginId),
      version: "0.0.0",
      private: true,
      type: "module",
      sideEffects: false,
      main: "./server.ts",
      exports: {
        ".": "./server.ts",
        "./server": "./server.ts",
        "./tui": "./tui.ts",
      },
      dependencies: {
        "@opencode-ai/plugin": "0.0.0-dev-18204",
        effect: "4.0.0-rc.111",
      },
      pioc: {
        generator: "@pi-oc2/target-opencode2@0.1.0",
        sourceCommit: "43dd33842ee70de0675ea3d1362b67b7dbff0051",
        sourceHash,
        targetProfile: OPENCODE2_TARGET_PROFILE,
      },
    }),
    null,
    2,
  )}\n`;
}

/** Emits the mergeable config fragment pointing directly at the generated Promise server. */
export function emitOpenCode2ConfigPatch(): string {
  return `{
  // Replace this placeholder with the absolute generated package path.
  "plugin": [
    "file://<generated-opencode2-package>/server.ts"
  ]
}
`;
}
