import type { PiToolAnalysis } from "@pi-oc2/core";
import { emitPiToolSchema } from "./pi-schema-emitter.js";

/** One validated tool and its portable default-export executor module. */
export interface PiToolEmission {
  readonly tool: PiToolAnalysis & { readonly name: string; readonly schema: NonNullable<PiToolAnalysis["schema"]> };
  readonly executorTargetPath: string;
}

const generatedHeaderLines = [
  "// Generated by @pi-oc2/target-pi v0.1.0.",
  "// Target profile: pi-0.84.3.",
  "// Generated files are disposable; edit pioc.port.json or portable sources instead.",
] as const;

function compareLexicalText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

/** Returns the local JavaScript import specifier for one copied portable executor source. */
export function piExecutorImportSpecifier(targetPath: string): string {
  const extension = /\.(?:cjs|cts|mjs|mts|tsx?|jsx?)$/u.exec(targetPath)?.[0];
  let emittedExtension = ".js";
  if (extension === ".cts") {
    emittedExtension = ".cjs";
  } else if (extension === ".mts") {
    emittedExtension = ".mjs";
  } else if (extension === undefined) {
    emittedExtension = "";
  }
  const withoutExtension = extension === undefined ? targetPath : targetPath.slice(0, -extension.length);
  return `./${withoutExtension}${emittedExtension}`;
}

/** Emits a standalone native Pi extension without importing OpenCode or a compatibility runtime. */
export function emitPiExtension(sourceHash: string, tools: readonly PiToolEmission[]): string {
  const executorTargetPaths = [...new Set(tools.map((entry) => entry.executorTargetPath))].sort(compareLexicalText);
  const executorIndexByTargetPath = new Map(executorTargetPaths.map((targetPath, index) => [targetPath, index]));
  const imports = executorTargetPaths.map(
    (targetPath, index) =>
      `import * as portableToolModule${index} from ${JSON.stringify(piExecutorImportSpecifier(targetPath))};`,
  );
  const registrations = tools.map((entry, index) => {
    const { tool } = entry;
    const executorIndex = executorIndexByTargetPath.get(entry.executorTargetPath);
    if (executorIndex === undefined) {
      throw new Error(`Pi extension emission invariant failed: executor import is missing for tool index ${index}.`);
    }
    return `  pi.registerTool({
    name: ${JSON.stringify(tool.name)},
    label: ${JSON.stringify(tool.name)},
    description: ${JSON.stringify(tool.description ?? tool.name)},
    parameters: ${emitPiToolSchema(tool.schema)},
    async execute(_toolCallId, params, signal, onUpdate, ctx) {
      const portableResult = await portableToolModule${executorIndex}.default(params, {
        cwd: ctx.cwd,
        signal: signal ?? new AbortController().signal,
        sessionId: ctx.sessionManager.getSessionId(),
        update(update) {
          onUpdate?.({
            content: update.text === undefined ? [] : [{ type: "text", text: update.text }],
            details: update.metadata,
          });
        },
      });
      return {
        content: [{ type: "text", text: portableResult.text }],
        details: portableResult.metadata,
      };
    },
  });`;
  });

  return [
    generatedHeaderLines[0],
    `// Source SHA-256: ${sourceHash}.`,
    ...generatedHeaderLines.slice(1),
    "",
    'import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";',
    'import { Type } from "typebox";',
    ...imports,
    "",
    "function StringEnum<const Values extends readonly string[]>(values: Values, options: Readonly<Record<string, unknown>> = {}) {",
    "  return Type.Unsafe<Values[number]>({ type: \"string\", enum: [...values], ...options });",
    "}",
    "",
    "export default function registerPortableTools(pi: ExtensionAPI): void {",
    ...registrations,
    "}",
    "",
  ].join("\n");
}
