import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { analyzePiPackage } from "@pi-oc2/core";
import { serializeStableJson } from "@pi-oc2/core/serialization";
import { runPortCommand } from "./port-command.js";
import { runVerifyCommand } from "./verify-command.js";
import { createTempDirectory, removeTempDirectory, writeFixtureManifest, writeFixturePiPackage } from "./test-support.js";

const cleanupDirectories: string[] = [];
afterEach(async () => {
  await Promise.all(cleanupDirectories.splice(0).map(removeTempDirectory));
});

async function tempDir(prefix: string): Promise<string> {
  const path = await createTempDirectory(prefix);
  cleanupDirectories.push(path);
  return path;
}

/** Runs a full, real `pioc port` against the real target generators and returns the resulting port. */
async function createVerifiedPort(): Promise<{ readonly source: string; readonly portDir: string; readonly manifestPath: string }> {
  const source = await tempDir("pioc-verify-source-");
  await writeFixturePiPackage(source);
  const analysis = await analyzePiPackage(source);
  if (!analysis.ok) {
    throw new Error("fixture package failed to analyze");
  }
  const portDir = await tempDir("pioc-verify-port-");
  const manifestPath = await writeFixtureManifest(portDir, analysis.value);

  await runPortCommand({ sourcePath: source, manifestPath, outDir: portDir });

  return { source, portDir, manifestPath };
}

describe("runVerifyCommand", () => {
  it("passes a freshly ported directory: regenerated bytes match and both real targets typecheck", async () => {
    const { portDir } = await createVerifiedPort();

    const result = await runVerifyCommand({ portDir, skipOpenCode2Smoke: true });

    expect(result.packageName).toBe("fixture");
    expect(result.piTypecheck).toBe("passed");
    expect(result.opencode2Typecheck).toBe("passed");
    expect(result.opencode2Smoke).toEqual({ status: "skipped", reason: "Skipped by caller." });
  }, 30_000);

  it("does not block verification on an ambient opencode2 that isn't the exact pinned dev-18204 build", async () => {
    const { portDir } = await createVerifiedPort();
    delete process.env.PIOC_OPENCODE2_BIN;

    // No skipOpenCode2Smoke override: exercises runOpenCode2ConfigDiscoverySmoke for real against
    // whatever opencode2 happens to be on PATH in this dev environment (v0.0.0-beta-18155) — the
    // exact "older ambient build" case opencode2-smoke.test.ts covers in isolation. The smoke check
    // must skip cleanly with a precise version reason, not report a false "passed" and not fail
    // verification outright.
    const result = await runVerifyCommand({ portDir });

    expect(result.piTypecheck).toBe("passed");
    expect(result.opencode2Typecheck).toBe("passed");
    expect(result.opencode2Smoke.status).toBe("skipped");
    if (result.opencode2Smoke.status === "skipped") {
      expect(result.opencode2Smoke.reason).toContain("0.0.0-dev-18204");
    }
  }, 30_000);

  it("rejects a port whose checked-in generated bytes no longer match what regenerates", async () => {
    const { portDir } = await createVerifiedPort();
    // Simulates someone hand-editing disposable generated output after `pioc port` ran.
    const extensionPath = join(portDir, "generated", "pi", "extension.ts");
    await writeFile(extensionPath, `${await readFile(extensionPath, "utf8")}\n// tampered\n`);

    const failure = await runVerifyCommand({ portDir, skipOpenCode2Smoke: true }).catch((error: unknown) => error);

    expect(failure).toMatchObject({ code: "PORT_TARGET_BYTES_DRIFT", exitCode: 1 });
    const details = (failure as { details: readonly string[] }).details;
    expect(details.some((detail) => detail.startsWith("generated/pi/extension.ts"))).toBe(true);
  }, 30_000);

  it("rejects a port directory with no pioc.lock.json", async () => {
    const portDir = await tempDir("pioc-verify-no-lock-");

    await expect(runVerifyCommand({ portDir, skipOpenCode2Smoke: true })).rejects.toMatchObject({
      code: "PORT_LOCK_NOT_FOUND",
      exitCode: 1,
    });
  });

  it("rejects a lock recorded against a different target profile than this pioc build", async () => {
    const { portDir } = await createVerifiedPort();
    const lockPath = join(portDir, "pioc.lock.json");
    const lock = JSON.parse(await readFile(lockPath, "utf8"));
    lock.targetProfile = "pi-0.1.0|opencode2:old";
    await writeFile(lockPath, serializeStableJson(lock));

    await expect(runVerifyCommand({ portDir, skipOpenCode2Smoke: true })).rejects.toMatchObject({
      code: "PORT_LOCK_TARGET_PROFILE_DRIFT",
      exitCode: 1,
    });
  });

  it("rejects a port whose source has changed since it was ported", async () => {
    const { source, portDir } = await createVerifiedPort();
    await writeFile(join(source, "extensions", "hello.ts"), "export default function (pi) {}\n// changed\n");

    await expect(runVerifyCommand({ portDir, skipOpenCode2Smoke: true })).rejects.toMatchObject({
      code: "PORT_LOCK_SOURCE_DRIFT",
      exitCode: 1,
    });
  });

  it("rejects a port whose manifest no longer resolves every required capability", async () => {
    const { portDir, manifestPath } = await createVerifiedPort();
    const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
    delete manifest.resolutions[Object.keys(manifest.resolutions)[0] as string];
    await writeFile(manifestPath, serializeStableJson(manifest));

    await expect(runVerifyCommand({ portDir, skipOpenCode2Smoke: true })).rejects.toMatchObject({
      code: "UNRESOLVED_REQUIRED_CAPABILITIES",
      exitCode: 1,
    });
  });
});
